const DB_NAME='travelDiaryDB';
const STORE='entries';
let editingId=null, existingPhoto=null, selectedLocation=null, map=null, marker=null, suggestionTimer=null, existingGallery=[];
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=e=>{const db=e.target.result;if(!db.objectStoreNames.contains(STORE)) db.createObjectStore(STORE,{keyPath:'id'});};req.onsuccess=e=>resolve(e.target.result);req.onerror=e=>reject(e.target.error);});}
async function saveEntry(entry){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(entry);tx.oncomplete=()=>res();tx.onerror=e=>rej(e);});}
async function getById(id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(id);req.onsuccess=()=>res(req.result);req.onerror=e=>rej(e);});}
const qs=new URLSearchParams(location.search);
const formTitle=document.getElementById('formTitle');
const placeLabelEl=document.getElementById('placeLabel');
const titleEl=document.getElementById('title');
const startDateEl=document.getElementById('startDate');
const endDateEl=document.getElementById('endDate');
const notesEl=document.getElementById('notes');
const photoEl=document.getElementById('photo');
const locationSearchEl=document.getElementById('locationSearch');
const searchLocationBtn=document.getElementById('searchLocationBtn');
const locationPreviewEl=document.getElementById('locationPreview');
const suggestionsEl=document.getElementById('suggestions');
const mapEl=document.getElementById('map');
const imageStatusEl=document.getElementById('imageStatus');
const coverPreviewEl=document.getElementById('coverPreview');
const saveBtn=document.getElementById('saveBtn');
const cancelEditBtn=document.getElementById('cancelEditBtn');
const errors={placeLabel:document.getElementById('placeLabelError'),title:document.getElementById('titleError'),startDate:document.getElementById('startDateError'),endDate:document.getElementById('endDateError'),location:document.getElementById('locationError')};
function compressImage(file,maxWidth=1400,quality=0.82){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const img=new Image();img.onload=()=>{const scale=Math.min(1,maxWidth/img.width);const canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',quality));};img.onerror=reject;img.src=fr.result;};fr.onerror=reject;fr.readAsDataURL(file);});}
function updateImageStatus(){if(photoEl.files&&photoEl.files.length){imageStatusEl.textContent=`New cover selected: ${photoEl.files[0].name}`;imageStatusEl.className='image-status has-image';const r=new FileReader();r.onload=()=>{coverPreviewEl.src=r.result;coverPreviewEl.classList.add('show');};r.readAsDataURL(photoEl.files[0]);return;}if(existingPhoto){imageStatusEl.textContent='Existing cover will be kept unless you choose a new one.';imageStatusEl.className='image-status has-image';coverPreviewEl.src=existingPhoto;coverPreviewEl.classList.add('show');return;}imageStatusEl.textContent='No image selected. You can add one later.';imageStatusEl.className='image-status';coverPreviewEl.classList.remove('show');coverPreviewEl.removeAttribute('src');}
function updateLocationPreview(){if(!selectedLocation){locationPreviewEl.textContent='No location selected yet.';return;}locationPreviewEl.innerHTML=`<strong>${selectedLocation.name||'Pinned location'}</strong><br>${selectedLocation.lat.toFixed(5)}, ${selectedLocation.lng.toFixed(5)}`;}
function setMarker(lat,lng){if(!map) return;if(!marker){marker=new maplibregl.Marker({color:'#2563eb'}).setLngLat([lng,lat]).addTo(map);}else{marker.setLngLat([lng,lat]);}}
function clearValidation(){[placeLabelEl,titleEl,startDateEl,endDateEl,locationSearchEl].forEach(el=>el.classList.remove('invalid'));Object.values(errors).forEach(e=>e.classList.remove('show'));}
function validateForm(){clearValidation();let ok=true;if(!placeLabelEl.value.trim()){placeLabelEl.classList.add('invalid');errors.placeLabel.classList.add('show');ok=false;}if(!titleEl.value.trim()){titleEl.classList.add('invalid');errors.title.classList.add('show');ok=false;}if(!startDateEl.value){startDateEl.classList.add('invalid');errors.startDate.classList.add('show');ok=false;}if(!endDateEl.value || (startDateEl.value && endDateEl.value < startDateEl.value)){endDateEl.classList.add('invalid');errors.endDate.classList.add('show');ok=false;}if(!selectedLocation){locationSearchEl.classList.add('invalid');errors.location.classList.add('show');ok=false;}return ok;}
function clearSuggestions(){suggestionsEl.style.display='none';suggestionsEl.innerHTML='';}
async function geocodePlace(query,limit=1){const url=`https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=${limit}&q=${encodeURIComponent(query)}`;const res=await fetch(url,{headers:{'Accept':'application/json'}});if(!res.ok) throw new Error('Location search failed');return res.json();}
function showSuggestions(items){suggestionsEl.innerHTML='';if(!items.length){clearSuggestions();return;}for(const item of items){const div=document.createElement('div');div.className='suggestion';div.textContent=item.display_name;div.addEventListener('mousedown',e=>{e.preventDefault();const lat=parseFloat(item.lat),lng=parseFloat(item.lon);selectedLocation={name:item.display_name,lat,lng};locationSearchEl.value=item.display_name;if(map){map.flyTo({center:[lng,lat],zoom:13});setMarker(lat,lng);}updateLocationPreview();locationSearchEl.classList.remove('invalid');errors.location.classList.remove('show');clearSuggestions();});suggestionsEl.appendChild(div);}suggestionsEl.style.display='block';}
function initMap(){try{map=new maplibregl.Map({container:'map',style:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm'}]},center:[10,20],zoom:1.6});map.addControl(new maplibregl.NavigationControl(),'top-right');map.on('load',()=>{mapEl.style.color='transparent';});map.on('click',e=>{selectedLocation={name:'Pinned location',lat:e.lngLat.lat,lng:e.lngLat.lng};setMarker(e.lngLat.lat,e.lngLat.lng);updateLocationPreview();locationSearchEl.classList.remove('invalid');errors.location.classList.remove('show');clearSuggestions();});}catch(e){mapEl.textContent='Map unavailable right now, but search still works.';}}
locationSearchEl.addEventListener('input',()=>{locationSearchEl.classList.remove('invalid');errors.location.classList.remove('show');clearTimeout(suggestionTimer);const q=locationSearchEl.value.trim();if(q.length<3){clearSuggestions();return;}suggestionTimer=setTimeout(async()=>{try{showSuggestions(await geocodePlace(q,5));}catch{clearSuggestions();}},180);});
document.addEventListener('click',e=>{if(!suggestionsEl.contains(e.target)&&e.target!==locationSearchEl) clearSuggestions();});
searchLocationBtn.addEventListener('click',async()=>{const q=locationSearchEl.value.trim();if(!q){locationSearchEl.classList.add('invalid');errors.location.classList.add('show');return;}try{const results=await geocodePlace(q,1);const r=results[0];if(!r){alert('No location found.');return;}selectedLocation={name:r.display_name,lat:parseFloat(r.lat),lng:parseFloat(r.lon)};if(map){map.flyTo({center:[selectedLocation.lng,selectedLocation.lat],zoom:13});setMarker(selectedLocation.lat,selectedLocation.lng);}updateLocationPreview();clearSuggestions();}catch{alert('Search failed.');}});
photoEl.addEventListener('change',updateImageStatus);
[placeLabelEl,titleEl,startDateEl,endDateEl].forEach(el=>el.addEventListener('input',()=>el.classList.remove('invalid')));
locationSearchEl.addEventListener('input',()=>errors.location.classList.remove('show'));
cancelEditBtn.addEventListener('click',()=>location.href='index.html');
saveBtn.addEventListener('click',async()=>{if(!validateForm()) return;let photo=existingPhoto;if(photoEl.files.length) photo=await compressImage(photoEl.files[0]);const existing=editingId?await getById(editingId):null;const startDate=startDateEl.value;const endDate=endDateEl.value;const durationDays=Math.max(1, Math.round((new Date(endDate)-new Date(startDate))/(1000*60*60*24))+1);const entry={id:editingId||crypto.randomUUID(),placeLabel:placeLabelEl.value.trim(),title:titleEl.value.trim(),startDate,endDate,durationDays,notes:notesEl.value.trim(),photo,gallery:existing?.gallery||existingGallery||[],location:selectedLocation,created:existing?existing.created:Date.now(),updated:Date.now()};await saveEntry(entry);location.href='index.html';});
(async function init(){initMap();updateLocationPreview();updateImageStatus();const id=qs.get('id');if(!id) return;const item=await getById(id);if(!item) return;editingId=id;existingPhoto=item.photo||null;existingGallery=item.gallery||[];selectedLocation=item.location||null;formTitle.textContent='Edit trip';saveBtn.textContent='Update trip';cancelEditBtn.style.display='inline-block';placeLabelEl.value=item.placeLabel||'';titleEl.value=item.title||'';startDateEl.value=item.startDate||'';endDateEl.value=item.endDate||'';notesEl.value=item.notes||'';locationSearchEl.value=item.location?.name||'';if(selectedLocation&&map){map.flyTo({center:[selectedLocation.lng,selectedLocation.lat],zoom:13});setMarker(selectedLocation.lat,selectedLocation.lng);}updateLocationPreview();updateImageStatus();})();
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{});}